apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-api-deployment
  labels:
    app: nginx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-api
  template:
    metadata:
      labels:
        app: nginx-api
    spec:
      containers:
        - name: nginx-api
          image: nginx-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7800
